### ISSUE TITLE
Dont finish compile cited 

### ISSUE THREAD

**Issue by mrdeathjr28** [acomminos/wine-pba#2]
Try build but crash cited iphlpapi error

**Comment by Armored87** [comment]
Configures ok but it's failing to compile for me as well, particularly when it comes to "wine-64-preloader" and "loader", screenshot attached for better illustration.

Build environment: Debian 9, compiling with --enable-win64 argument.

![error](https://user-images.githubusercontent.com/13750621/36622669-b912248c-18fe-11e8-981d-9542520d4ede.jpg)

**Comment by ChrisJAllan** [comment]
Running `autoconf` before `configure` fixes that issue, but there are others that still prevent it from compiling, eg: 
```
error: unknown type name ‘shmglobal_t’
```
repeated many times, and
```
async.c:385:40: error: ‘COMPLETION_SKIP_ON_SUCCESS’ undeclared (first use in this function); did you mean ‘IO_COMPLETION_ALL_ACCESS’?
```

**Comment by acomminos** [comment]
Ah, so this is what happens when you omit build files modified by the wine-staging patcher.

Give me ~1 hour or so and I'll alter this repo to just include a set of patches, rather than a fork.

**Comment by acomminos** [comment]
Done- let me know how it goes.

**Comment by mrdeathjr28** [comment]
Hi

I can test your patch with vanilla but at patch moment, first 2 patchs apply without issues

In first patch have delete: 

dlls/wined3d-csmt/Makefile.in  |   1 +

diff --git a/dlls/wined3d-csmt/Makefile.in b/dlls/wined3d-csmt/Makefile.in
index bf064ed16f..cab1e6fdc1 100644
--- a/dlls/wined3d-csmt/Makefile.in
+++ b/dlls/wined3d-csmt/Makefile.in
@@ -8,6 +8,7 @@ C_SRCS = \
 	arb_program_shader.c \
 	ati_fragment_shader.c \
 	buffer.c \
+	buffer_heap.c \
 	context.c \
 	cs.c \
 	device.c \

change

6 files changed, 364 insertions(+), 4 deletions(-)

to

5 files changed, 363 insertions(+), 4 deletions(-)


But 3 patch shows issues

Shows reject in 5 elements: buffer.c - cs.c - resource.c - texture.c and wined3d_private.h

In reject file for each file shows this


buffer.c

--- dlls/wined3d/buffer.c
+++ dlls/wined3d/buffer.c
@@ -864,6 +945,8 @@ static void wined3d_buffer_destroy_object(void *object)
         HeapFree(GetProcessHeap(), 0, buffer->conversion_map);
     }
 
+    buffer_free_persistent_map(buffer);
+
     HeapFree(GetProcessHeap(), 0, buffer->maps);
     HeapFree(GetProcessHeap(), 0, buffer);
 }
@@ -1517,8 +1702,10 @@ static const struct wined3d_resource_ops buffer_resource_ops =
     buffer_resource_preload,
     buffer_unload,
     buffer_resource_sub_resource_map,
+    buffer_resource_sub_resource_map_cs,
     buffer_resource_sub_resource_map_info,
     buffer_resource_sub_resource_unmap,
+    buffer_resource_sub_resource_unmap_cs,
 };
 
 static GLenum buffer_type_hint_from_bind_flags(const struct wined3d_gl_info *gl_info,


cs.c

--- dlls/wined3d/cs.c
+++ dlls/wined3d/cs.c
@@ -73,6 +73,7 @@ enum wined3d_cs_op
     WINED3D_CS_OP_COPY_UAV_COUNTER,
     WINED3D_CS_OP_COPY_SUB_RESOURCE,
     WINED3D_CS_OP_GENERATE_MIPS,
+    WINED3D_CS_OP_DISCARD_BUFFER,
     WINED3D_CS_OP_STOP,
 };
 
@@ -2746,6 +2803,7 @@ static void (* const wined3d_cs_op_handlers[])(struct wined3d_cs *cs, const void
     /* WINED3D_CS_OP_COPY_UAV_COUNTER            */ wined3d_cs_exec_copy_uav_counter,
     /* WINED3D_CS_OP_COPY_SUB_RESOURCE           */ wined3d_cs_exec_copy_sub_resource,
     /* WINED3D_CS_OP_GENERATE_MIPS               */ wined3d_cs_exec_generate_mips,
+    /* WINED3D_CS_OP_DISCARD_BUFFER              */ wined3d_cs_exec_discard_buffer,
 };
 
 #if defined(STAGING_CSMT)


resource.c

--- dlls/wined3d/resource.c
+++ dlls/wined3d/resource.c
@@ -358,13 +358,18 @@ static DWORD wined3d_resource_sanitise_map_flags(const struct wined3d_resource *
 HRESULT CDECL wined3d_resource_map(struct wined3d_resource *resource, unsigned int sub_resource_idx,
         struct wined3d_map_desc *map_desc, const struct wined3d_box *box, DWORD flags)
 {
+    HRESULT hr;
     TRACE("resource %p, sub_resource_idx %u, map_desc %p, box %s, flags %#x.\n",
             resource, sub_resource_idx, map_desc, debug_box(box), flags);
 
     flags = wined3d_resource_sanitise_map_flags(resource, flags);
-    wined3d_resource_wait_idle(resource);
-
-    return wined3d_cs_map(resource->device->cs, resource, sub_resource_idx, map_desc, box, flags);
+    if (FAILED(hr = resource->resource_ops->resource_sub_resource_map(resource, sub_resource_idx, map_desc, box, flags)))
+    {
+        TRACE_(d3d_perf)("Mapping resource %p on the command stream.\n", resource);
+        wined3d_resource_wait_idle(resource);
+        hr = wined3d_cs_map(resource->device->cs, resource, sub_resource_idx, map_desc, box, flags);
+    }
+    return hr;
 }
 
 HRESULT CDECL wined3d_resource_map_info(struct wined3d_resource *resource, unsigned int sub_resource_idx,


texture.c

--- dlls/wined3d/texture.c
+++ dlls/wined3d/texture.c
@@ -2525,8 +2536,10 @@ static const struct wined3d_resource_ops texture_resource_ops =
     texture_resource_preload,
     wined3d_texture_unload,
     texture_resource_sub_resource_map,
+    texture_resource_sub_resource_map_cs,
     texture_resource_sub_resource_map_info,
     texture_resource_sub_resource_unmap,
+    texture_resource_sub_resource_unmap_cs,
 };
 
 static HRESULT texture1d_init(struct wined3d_texture *texture, const struct wined3d_resource_desc *desc,


wined3d_private.h

--- dlls/wined3d/wined3d_private.h
+++ dlls/wined3d/wined3d_private.h
@@ -3013,9 +3016,12 @@ struct wined3d_resource_ops
     void (*resource_unload)(struct wined3d_resource *resource);
     HRESULT (*resource_sub_resource_map)(struct wined3d_resource *resource, unsigned int sub_resource_idx,
             struct wined3d_map_desc *map_desc, const struct wined3d_box *box, DWORD flags);
+    HRESULT (*resource_sub_resource_map_cs)(struct wined3d_resource *resource, unsigned int sub_resource_idx,
+            struct wined3d_map_desc *map_desc, const struct wined3d_box *box, DWORD flags);
     HRESULT (*resource_map_info)(struct wined3d_resource *resource, unsigned int sub_resource_idx,
             struct wined3d_map_info *info, DWORD flags);
     HRESULT (*resource_sub_resource_unmap)(struct wined3d_resource *resource, unsigned int sub_resource_idx);
+    HRESULT (*resource_sub_resource_unmap_cs)(struct wined3d_resource *resource, unsigned int sub_resource_idx);
 };
 
 struct wined3d_resource
@@ -3627,6 +3634,7 @@ void wined3d_cs_emit_copy_sub_resource(struct wined3d_cs *cs, struct wined3d_res
         unsigned int dst_sub_resource_idx, const struct wined3d_box *dst_box, struct wined3d_resource *src_resource,
         unsigned int src_sub_resource_idx, const struct wined3d_box *src_box) DECLSPEC_HIDDEN;
 void wined3d_cs_emit_generate_mips(struct wined3d_cs *cs, struct wined3d_shader_resource_view *view) DECLSPEC_HIDDEN;
+void wined3d_cs_emit_discard_buffer(struct wined3d_cs *cs, struct wined3d_buffer *buffer, struct wined3d_map_range map_range) DECLSPEC_HIDDEN;
 void wined3d_cs_init_object(struct wined3d_cs *cs,
         void (*callback)(void *object), void *object) DECLSPEC_HIDDEN;
 HRESULT wined3d_cs_map(struct wined3d_cs *cs, struct wined3d_resource *resource, unsigned int sub_resource_idx,


Thanks
