### ISSUE TITLE
A significant StarCraft 2 FPS regression with the Wine-PBA and my AMD Radeon HD7770.

### ISSUE THREAD

**Issue by Kerrung** [acomminos/wine-pba#21]
I have a significant FPS regression when I'm testing x64 StarCraft 2 with the Wine-PBA.
Arch Linux with the latest updates.
With my graphical settings and my AMD Radeon HD7770 with AMDGPU+Mesa:

Wine Staging vanilla: ~40fps
Wine Staging + PBA: ~4-7fps

If I see that in one of the PBA updates it will be fixed I will write about it here.
Please tell me if you need any logs.

In addition to SC2, I tested two more games.
World of Warcraft - there are no significant FPS changes with PBA, or without it.
The Witcher 3 - there are no all character models when I use PBA.

Thank you very match for your work!

**Comment by Kerrung** [comment]
With commit 7ebfd60
Wine Staging 3.3 vanilla: ~40fps
Wine Staging 3.3 + PBA: ~14fps
Wine Staging 3.3 + Gallium Nine ~70fps, but sometimes there are crashes and it works only with d3d9, not with d3d10 or d3d11.

**Comment by acomminos** [comment]
Thanks for the data. Can you post a profile of execution using `perf record` (with debugging symbols available, please)?

Thanks!

**Comment by acomminos** [comment]
Also, if you could test 1bc7015, that would be great. A brief look at the radeon gallium driver suggests it may help with streaming.

**Comment by Kerrung** [comment]
>Also, if you could test 1bc7015, that would be great. A brief look at the radeon gallium driver suggests it may help with streaming.

Wine Staging 3.3 vanilla: ~25~40fps
Wine Staging 3.3 + PBA With commit 1bc7015 : ~40~60fps

>Thanks for the data. Can you post a profile of execution using perf record (with debugging symbols available, please)?
Thanks!

I will try to do this a little later, but I do not have this experience. I measured fps in SC2 using the in game built-in FPS counter.

**Comment by acomminos** [comment]
Glad that worked for you.

Closing this.
