### ISSUE TITLE
It is necessary to update the PBA patches to compatibility with Wine Staging 3.3

### ISSUE THREAD

**Issue by Kerrung** [acomminos/wine-pba#22]
Wine Staging 3.3 released.
It is necessary to update the PBA patches to compatibility with it.
The source code of the new Wine Staging can be downloaded here:
https://github.com/wine-staging/wine-staging
Thank you!

**Comment by Firerat** [comment]
patchset for  wine-devel_3.3 with staging 3.3 "patchinstall.sh --all" applied
it compiles, both 32 and 64bit builds
as for functionality, not really tested

[wine-pba-for_staging_v3.3.tar.gz](https://github.com/acomminos/wine-pba/files/1781950/wine-pba-for_staging_v3.3.tar.gz)
have fun :)

**Comment by acomminos** [comment]
Done.
