### ISSUE TITLE
I can not compile a commit 1bc7015

### ISSUE THREAD

**Issue by Kerrung** [acomminos/wine-pba#24]
I can not compile a commit 1bc7015:

include/wine/server_protocol.h updated
server/trace.c updated
server/request.h updated
~/Other/wine-testing/Staging-pda/src
can't find file to patch at input line 24
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 1f69076549bf2351eb6d8d885b35a46b4dc69813 Mon Sep 17 00:00:00 2001
|From: Andrew Comminos <andrew@comminos.com>
|Date: Mon, 5 Mar 2018 15:38:35 -0800
|Subject: [PATCH 1/4] wined3d: Initial implementation of a persistent mapped
| buffer allocator.
|
|---
| dlls/wined3d-csmt/Makefile.in  |   1 +
| dlls/wined3d/Makefile.in       |   1 +
| dlls/wined3d/buffer_heap.c     | 508 +++++++++++++++++++++++++++++++++++++++++
| dlls/wined3d/cs.c              |   9 +
| dlls/wined3d/device.c          |  52 +++++
| dlls/wined3d/directx.c         |   3 +
| dlls/wined3d/query.c           |   2 +-
| dlls/wined3d/wined3d_gl.h      |   1 +
| dlls/wined3d/wined3d_private.h |  68 +++++-
| 9 files changed, 641 insertions(+), 4 deletions(-)
| create mode 100644 dlls/wined3d/buffer_heap.c
|
|diff --git a/dlls/wined3d-csmt/Makefile.in b/dlls/wined3d-csmt/Makefile.in
|index 1d0458eb46..cb3a5484c6 100644
|--- a/dlls/wined3d-csmt/Makefile.in
|+++ b/dlls/wined3d-csmt/Makefile.in
--------------------------
File to patch:

**Comment by stefson** [comment]
please give us the whole build.log - my guess would be that you try to apply the patches either against the old wine-2.2x or against wine-3.x without the staging patches applied before.

**Comment by Kerrung** [comment]
> please give us the whole build.log - my guess would be that you try to apply the patches either against the old wine-2.2x or against wine-3.x without the staging patches applied before.

Arch Linux.
Wine Staging 3.3.
The previous commit was compiled without any problems.

**Comment by stefson** [comment]
build log please.

**Comment by Kerrung** [comment]
> build log please.

[build-log.txt](https://github.com/acomminos/wine-pba/files/1785260/build-log.txt)

**Comment by stefson** [comment]
So, I checked for you that the patches from here do not interfere with the d3d9 patches and that you have applied staging patches before. Where did you got that aur build script from? Fact is that the problem must be at your end, because the patches do apply just fine for everyone else.

**Comment by Kerrung** [comment]
I downloaded PKGBUILD from the official Arch Linux repository and then modified it to add VB:
https://www.archlinux.org/packages/multilib/x86_64/wine-staging/
Part I took from here to add Gallium Nine patches:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wine-gaming-nine
https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/wine-staging-nine
[PKGBUILD.zip](https://github.com/acomminos/wine-pba/files/1785440/PKGBUILD.zip)

**Comment by Kerrung** [comment]
>So, I checked for you that the patches from here do not interfere with the d3d9 patches and that you have applied staging patches before. Where did you got that aur build script from? Fact is that the problem must be at your end, because the patches do apply just fine for everyone else.

I realized what my mistake was.
- in the directory path in PKGBUILD for some reason makes the path wrong.
The compilation started right away as soon as I removed the dash characters from the path.
Thank you. I close this issue.
