### ISSUE TITLE
The Witcher 3 with PBA tests

### ISSUE THREAD

**Issue by Kerrung** [acomminos/wine-pba#29]
With PBA commit b33e274 when The Witcher 3 starts it totally hangs my o.s. with only black screen and I had to hard reboot. With the previous PBA commits, I did not have such a issue.
Arch Linux with latest updates.
AMD Radeon 7770 with amdgpu+Mesa 17.3.6.
Wine Staging 3.3 with PBA commit b33e274.

**Comment by thirdeyefunction** [comment]
I can confirm this. Affects both an AMD RX 550 with Mesa git and a Nvidia 980ti with the 390x binary drivers. In the Mesa case it's pretty much unrecoverable, although I can at least SSH in and use /proc/sysrq-trigger to clean up before rebooting. With the nvidia card, I can kill X via SSH and recover from it.

**Comment by Kerrung** [comment]
Please, I would like to see the developer's comment so that we can know that he is already aware of this issue.

**Comment by Firerat** [comment]
does this only happen with pba?
what happens with wine-devel-3.3 and wine-staging-3.3 ?
might not be pba
please confirm

**Comment by Kerrung** [comment]
>does this only happen with pba?
what happens with wine-devel-3.3 and wine-staging-3.3 ?
might not be pba
please confirm

It only happen with pba, and only since commit b33e274.
With the previous PBA commits, I did not have such a issue.

**Comment by Kerrung** [comment]
The Witсher 3 is a drm-free game, so you can try to test it how it works.

**Comment by Kerrung** [comment]
The Witсher 3 is a drm-free game, so you can try to test it how it works with Wine-PBA patches.
But this still leads to a total hang of the operating system with black screen and loss of control of the keyboard.

**Comment by AndersDala** [comment]
Same here. Nvidia 390.25

Black screen, no keyboard, ssh in or hard-reboot

**Comment by Kerrung** [comment]
If you do not have this game, It's a magnet link for download TW3, a drm-free game.
It can be copied and added to any torrent client, only for testing how this game works, of course.

magnet:?xt=urn:btih:BC2930B589F0484F93F508DFEC5232048448CEA5&tr=http%3A%2F%2Fbt2.t-ru.org%2Fann%3Fmagnet&dn=The%20Witcher%203%3A%20Wild%20Hunt%20-%20Game%20of%20the%20Year%20Edition%20%2B%20HD%20Reworked%20Project%20%5BRePack%5D%20%5BRUS%20%2B%20ENG%20%2F%20RUS%20%2B%20ENG%5D%20(2015)%20(1.31.0)%20%5BMOD%5D

**Comment by kiljacken** [comment]
@Kerrung Please do not share pirated games on GitHub. I'd suggest you delete your magnet link before you get yourself banned :)

**Comment by Kerrung** [comment]
> @Kerrung Please do not share pirated games on GitHub. I'd suggest you delete your magnet link before you get yourself banned :)

Fixed, tnx.

**Comment by acomminos** [comment]
FWIW, this is next on my list to address.

**Comment by acomminos** [comment]
I've disabled the hacky implementation of persistent shader resource buffers in 3d8fe71. This should fix these issues, but won't actually use the PBA for (a small number of) buffers in TW3.

**Comment by Kerrung** [comment]
>I've disabled the hacky implementation of persistent shader resource buffers in 3d8fe71. This should fix these issues, but won't actually use the PBA for (a small number of) buffers in TW3.

Is this a temporary solution that will exist only until the moment, until you make a full implementation?

**Comment by acomminos** [comment]
> Is this a temporary solution that will exist only until the moment, until you make a full implementation?

Yes. It's a bit trickier to avoid driver overhead with that path, it'll take some more thinking.

**Comment by thirdeyefunction** [comment]
Just tested the most recent commits. The game no longer crashes, but now vegetation isn't being rendered and performance seems to be lower but with a massive GPU load (99% on a 980ti at 1440p). Normally that would be a good sign, but framerate is only at 20fps or so. Not sure if it's due to 3d8fe71 or one of the other recent commits.

**Comment by GloriousEggroll** [comment]
as of today on vega 64 mesa-git 18.1, witcher 3 runs great, around 80 fps on high settings, 50 on ultra, 1080p. Renders properly. note: mesa needs MaxVersionGL set in registry as dword with hexadecimal value 40005, otherwise it wont render correctly.
![witcher 3](https://user-images.githubusercontent.com/11287837/37237319-a75a373e-23df-11e8-9c4a-ecdd51b63cfc.png)

**Comment by thirdeyefunction** [comment]
That screenshot looks like the results I'm getting (except for the good performance). Note how there is no vegetation at all.

**Comment by Kerrung** [comment]
> I've disabled the hacky implementation of persistent shader resource buffers in 3d8fe71. This should fix these issues, but won't actually use the PBA for (a small number of) buffers in TW3.

With commit 3d8fe71 The Witcher no longer causes a hang. Thank you!

**Comment by GloriousEggroll** [comment]
unsure why this was closed, as the vegetation rendering is still a problem
