### ISSUE TITLE
steps to compile

### ISSUE THREAD

**Issue by SteveEbey73742** [acomminos/wine-pba#31]
can you tell me what order I need to patch and compile.  I am not clear how to apply the patches from here, to staging, and do I do it after staging patches are applied to the devel source?

**Comment by xpander69** [comment]
This is not an issue post afaik, doesnt go with wine-pba 
but you patch like you patch it with other things you compile
 ```
 patch -Np1 < 0001-wined3d-Initial-implementation-of-a-persistent-mappe.patch
  patch -Np1 < 0002-wined3d-Add-support-for-backing-dynamic-wined3d_buff.patch
  patch -Np1 < 0003-wined3d-Use-ARB_multi_bind-to-speed-up-UBO-updates.patch
  patch -Np1 < 0004-wined3d-Use-GL_CLIENT_STORAGE_BIT-for-persistent-map.patch
```
and then your regular ./configure and  make and make install

**Comment by Firerat** [comment]
Hi, I will try and fill in some blanks for youget wine-devel source, staging patches and pba
`git clone git://source.winehq.org/git/wine.git
git clone https://github.com/wine-staging/wine-staging.git
git clone https://github.com/acomminos/wine-pba.git `
now we need to patch wine-devel 3.3 with staging 3.3
_optional , to see stuff going. on_
`cd wine-staging
git checkout v3.3
cd ../wine;git checkout wine-3.3
../wine-staging/patches/patchinstall.sh --all `
all patches should apply,
now we shall commit to a new, local branch
`git checkout -b wine-staging-v3.3
_git status
git diff_
git add ./
_git status_
git commit -m "wine staging v3.3"
_git status
git log
git log -p
git diff wine-3.3_
`
now pba patches
`git apply ../wine-pba/patches/000*
_git status
git diff_
`
 
for compiling, see
https://wiki.winehq.org/Building_Wine
 
the containers section is well worth a read
https://wiki.winehq.org/Building_Wine#Containers
 
I will also recommend ccache, and if you have access to multiple machines..  distcc

**Comment by SteveEbey73742** [comment]
thank you all. I realize it was not a issue, but the help is most definitely appreciated.
