### ISSUE TITLE
Please, add a licence. Without any licence your project is proprietary by default

### ISSUE THREAD

**Issue by Kerrung** [acomminos/wine-pba#33]
Please, add a licence.
According to the licensing rules if your project have not any licence, so your project is proprietary by default.

**Comment by kiljacken** [comment]
Your message would come through better if you didn't attempt to force your
favorite license on the author :)

**Comment by Kerrung** [comment]
>Your message would come through better if you didn't attempt to force your
favorite license on the author :)

Fixed, tnx

**Comment by acomminos** [comment]
Done in c71766666e4da8cef7b44ae7335ff134d605858f.
