### ISSUE TITLE
For testing purposes - wine-pba + wine-staging-git

### ISSUE THREAD

**Issue by SveSop** [acomminos/wine-pba#46]
I will try to keep wine-pba rebased to work with wine-git + wine-staging-git
[https://github.com/SveSop/wine-pba-rebased](https://github.com/SveSop/wine-pba-rebased)

I also have a wine-staging-pba-patched repo available that is pre-patched with staging + pba.
[https://github.com/SveSop/wine-staging-pba-patched](https://github.com/SveSop/wine-staging-pba-patched)

As for both of these i will try to update when new patches arrives.. until something breaks i guess :)
This is mostly for own learning and testing, so stuff might break.

**Comment by Firerat** [comment]
keep some things out of the git repo
```
cat >> .gitignore << EOF 
.gitignore
autom4te.cache
include/config.h.in~
EOF
```
should probably add a few other things, like configure so it forces people to use a cleanly generated one.

for staging it is probably easier to use the [wine-patched repo](https://github.com/wine-staging/wine-patched/tree/master) it only updates on tags

Personally this is how I would set it up for outputting patches
```
git clone ....... wine-patched.git
git tag wine-staging-$(sed 's/Wine version //' VERSION)
git checkout wine-staging-$(sed 's/Wine version //' VERSION) # now in a detached head
git am --3way /path/to/wine-pba/patches/0* 
# fix any conflicts
git format-patch -o <dir> wine-staging-$(sed 's/Wine version //' VERSION)
git checkout master

```
if you really like the results , keep it `git branch -b I_like_this_one`

another way,  if you want to keep a patched branch around, with tags
```
git clone ....... wine-patched.git
cd wine-patched
git checkout master # but should already be on it
git tag wine-staging-$(sed 's/Wine version //' VERSION)
git checkout -b PBA-master
git am --3way /path/to/wine-pba/patches/0* # should clean apply
git log # have a look, maybe add a -p
git tag wine-staging-PBA-$(sed 's/Wine version //' VERSION)
git format-patch -o <dir> wine-staging-<tag> # unfuzzed patches
```
so, every two weeks wine-patched will get updated with the latest wine-devel

```
git checkout master
git pull
git tag wine-staging-$(sed 's/Wine version //' VERSION)
git checkout PBA-master # no -b this time
git rebase master # that will rewind the pba patches , 
                              # pull the master in and then reapply changes
#fix any merge conflicts, test stuff etc.
git tag wine-staging-PBA-$(sed 's/Wine version //' VERSION)
git log 
git format-patch ......
```

you could do the same with wine-devel+staging
```
git checkout master
git pull
git tag <sometag>
git checkout <sometag> # now detached
../wine-staging/patches/patchinstall.sh --all --backend=git-am --force-autoconf
staginghead=$(cat .git/HEAD) # 
git am --3way /path/to/wine-pba/patches/0*
git format-patch -o <dir> $staginghead
```

I may have rambled a bit , hope you get the idea

**Comment by SveSop** [comment]
Thanks for the tips. Added a .gitignore file, and deleted the autom4te.cache folder and the config.h.in~

Most of that other stuff sounds way too advanced for me to bother with, and i did not quite get what was up with the wine-patched repo.. Is that a patched version of wine-git each commit?

**Comment by Firerat** [comment]
https://github.com/wine-staging/
two repos, one is the staging patches, the other is wine-devel already patched

it is only updated with each wine-devel tag , last update was 7 days ago then next will be in 7 days
( wine is tagged every two weeks )

nah, it might look advanced ,, but it isn't ..
once you understand it a little better it will seem beautifully simple

regards the git-am, the reason I prefer that is  each staging patch gets its own commit
If I need to review the commit history of a file ( or file set ) I can see who changed what, when and why ( providing they said so in the commit msg )
 
at the moment you are using patchinstall.sh's default backend ,bog standard patch, so staging is one huge commit.. difficult to see the who,what,when,why 
 the `backend=git-am` does take longer to apply, but so much better when you need to work out what is going on

ofc, if you only worry about the 2week release cycle then https://github.com/wine-staging/wine-patched  has the full commit history ( same as --backend=git-am )

**Comment by shmerl** [comment]
So I can try using https://github.com/SveSop/wine-pba-rebased with Wine master?

**Comment by Firerat** [comment]
wine master ? you mean wine-devel without staging ?
yeah
use `git am --3way` instead of the patch script
e.g.
```
git am --3way patches/0*patch
# it will quickly stop
git status
# you should see dlls/wined3d-csmt/Makefile.in
git rm dlls/wined3d-csmt/Makefile.in
git am --continue
# rest should be ok, at least with wine-devel-3.4 it is
```

**Comment by shmerl** [comment]
OK, I placed patches in patches/ under Wine source tree. Checkout out wine-3.4 and try running the above. Then I got:

```
Applying: wined3d: Initial implementation of a persistent mapped buffer allocator.
error: sha1 information is lacking or useless (dlls/wined3d-csmt/Makefile.in).
error: could not build fake ancestor
Patch failed at 0001 wined3d: Initial implementation of a persistent mapped buffer allocator.
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

git status shows:
```
HEAD detached at wine-3.4
You are in the middle of an am session.
  (fix conflicts and then run "git am --continue")
  (use "git am --skip" to skip this patch)
  (use "git am --abort" to restore the original branch)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        patches/

nothing added to commit but untracked files present (use "git add" to track)
```

```
git rm dlls/wined3d-csmt/Makefile.in
fatal: pathspec 'dlls/wined3d-csmt/Makefile.in' did not match any files
```

**Comment by Firerat** [comment]
meh, might be because I have staging in my git repo, so git knows about it
ok
edit the 0001 patch, delete  lines 20 to 31
i.e.
```
diff --git a/dlls/wined3d-csmt/Makefile.in .....
....
     device.c \
```
abort the git am `git am --abort`
try again

**Comment by shmerl** [comment]
Nope, that didn't help much. Did you actually test it with wine-3.4 or Wine master?

**Comment by Firerat** [comment]
nah, no real point in chasing master
it is probably something trivial
I've just finished backporting 3.4 to 2.21, so I'll have a look now

**Comment by Firerat** [comment]
here you go
[pba-for-5946973.tar.gz](https://github.com/acomminos/wine-pba/files/1844967/pba-for-5946973.tar.gz)

@SveSop  your patch 0008 is wrong, should have byte padding of 2

**Comment by shmerl** [comment]
Yep, that worked directly by running patch to all of them with Wine master. Building it now to test.

**Comment by Firerat** [comment]
I forgot to say, that one has a little bonus in it
you can change the heap sizes 
https://github.com/Firerat/wine-pba/tree/heap_size_envvars

**Comment by shmerl** [comment]
Here is the result with The Witcher 3. Performance is better than stock wine, but worse than dxvk. Plus there seem to be rendering issues (lot's of things look missing):

![tw3_pba](https://user-images.githubusercontent.com/310927/37871202-a7221ff6-2fb6-11e8-9a67-8ad42e9c928f.jpg)

**Comment by Firerat** [comment]
you could try tweaking the heap sizes
-  `__PBA_GEO_HEAP` and `__PBA_CB_HEAP` envvars available
    - allows you to tweak the heap sizes without recompiling, which resolves problems with at least one game _FF XIV in d3d9 mode_
    [upstream issue 36 fix suggestion ](https://github.com/acomminos/wine-pba/issues/36#issuecomment-372079218)
    [upstream issue 36 fix confirmation ](https://github.com/acomminos/wine-pba/issues/36#issuecomment-372148581)
    since d3d9 does not use Constant Buffers `__PBA_CB_HEAP=1` would make sense 

at the moment your CB_HEAP is 128, try increasing it a little 
I assume it is DX11 and not 9

**Comment by shmerl** [comment]
I tried  `__PBA_CB_HEAP=256`. It doesn't seem to make any difference.

**Comment by Firerat** [comment]
ok, 
what if you set that back to 128 and up the GEO a bit

**Comment by shmerl** [comment]
What are defaults?

**Comment by Firerat** [comment]
geo 512 and cb 128

**Comment by shmerl** [comment]
Setting this finally made vegetation appear: `__PBA_GEO_HEAP=2048 __PBA_CB_HEAP=1024`

**Comment by Firerat** [comment]
nice
need to graph out the sweetspot, and have PBA default to that
what is your video ram?

sadly I can't really test stuff like this, I have a potato PC/gfx

**Comment by shmerl** [comment]
8GB VRAM.

**Comment by SveSop** [comment]
@Firerat @shmerl I guess those __PBA_GEO_HEAP stuff belongs in a own thread for usage, so going to close this thread as it is no longer of use.
