### ISSUE TITLE
Civilization 5 DirectX 11 mode not functional

### ISSUE THREAD

**Issue by ryanmusante** [acomminos/wine-pba#48]
In standard wine 3.x, Civilization 5 runs with \dx11 mode. Staging/pba will only load with \dx9 otherwise will crash to black screen and/or freeze system requiring reboot. Anyone else experiencing this?

**Comment by Kerrung** [comment]
https://github.com/doitsujin/dxvk

**Comment by Firerat** [comment]
I don't have civ5
you could try https://github.com/acomminos/wine-pba/issues/47
assuming you have plenty of vram  start with GEO 2048 CB 512 ( it should make more sense once you read that thread )
when you say crash.. can you get in via ssh ? 
you may be able to kill civ5 and not have to reboot

**Comment by ryanmusante** [comment]
I will try with geo heap/cbheap and also try dxvk to see if if it runs through that. Otherwise, dx9 mode is fine.

**Comment by Firerat** [comment]
if you still get no joy, you can try turning PBA off
`PBA_DISABLE=1 wine ....`
it should just work like upstream wine then
