### ISSUE TITLE
Here's a working wine-pba for latest 3.4 staging (the one with no CSTM_Helper, etc) 

### ISSUE THREAD

**Issue by goldpaw** [acomminos/wine-pba#50]
So I went a little over the top and set up some local repos at my comptuer last night, with wine, wine-staging, a wine-staging patched wine, and a final version where I manually added the pba code to a duplicate of the staging patched wine. Then I ran a diff of the two latter, and ended up with a single patch file meant to be applied to the lastest wine-staging patched wine. 

Works like a charm! :)

[wine-staging-pba.zip](https://github.com/acomminos/wine-pba/files/1859123/wine-staging-pba.zip)

**Comment by Thaodan** [comment]
Which wine-staging commit do you used?

**Comment by schtufbox** [comment]
If goldpaw is the same guy that does the AUR for arch, it pulls in from staging-git.  I just compiled wine-pba-staging from git this morning as there were a couple more rebased patches in staging....worked fine :)

**Comment by goldpaw** [comment]
Hey there, yes. I'm the user cogwerkz over at the AUR. And you're you. :) 

My sources are:
wine: git://source.winehq.org/git/wine.git
wine-staging: https://github.com/wine-staging/wine-staging

Just ran my script, and it reports the wine-staging commit to be
4e3fb17588bf0fb75d51a2380f8e43ce97cff57d, to answer your question @Thaodan . 

I think I might have used their previous commit on the file I attached here, but there are litterally no changes since then, my new patchfile has the exact same sha256sum as the previous.

I'll be keeping the patch file from my script in my fork of wine-pba, for those interested: 
https://github.com/goldpaw/wine-pba

**Comment by IngeniousDox** [comment]
We will be getting Wine 3.5 soon, and staging 3.5. So a proper rebase would be nice. Andrew said he was going to rebase it soon himself. So I figure we will see that.

However, the firerat patch that allows you to change the GEO / CB heaps with ENV vars is great aswell. Since then you can make wine-pba work with multiple games that don't work with the standard values for those heaps.

So I would suggest people clone the offical wine-pba repo, then make PRs with changes so it can be reviewed and added to the main repo. Andrew doesn't have as much time as he wants to make changes, but he said he would accept good PRs. And this is much cleaner then getting multiple repos with patches that have to be applied to other patches etc etc.

**Comment by Thaodan** [comment]
@goldpaw mine are the same but I had used the the sha from patchinstall and the patches doesn't applied cleanly. 

I think @Dox is right you should make a pr with your rebase. 
Make a separate branch that describes your changes and make a descriptive commit message.

**Comment by goldpaw** [comment]
Branch instead of a fork. That can be done. :+1:

**Comment by IngeniousDox** [comment]
Well, you fork wine-pba, create a new branch there with your changes. Then make a pull request at the main repo with your branch.

**Comment by TomBZombie** [comment]
I can't get 3.5 to work. I'm not sure if this is a problem with wine-staging or wine-pba.

The problem I have is this:

```
0009:fixme:module:load_dll Loader redirect from L"wined3d.dll" to L"wined3d-csmt.dll"
0009:err:module:import_dll Library wined3d.dll (which is needed by L"C:\\windows\\system32\\d3d8.dll") not found
```

There's a thread here: https://www.reddit.com/r/wine_gaming/comments/88m1mz/wine_staging_35_released/ where someone has the same issue and suggests unticking CSMT. If I do that,  and press apply it's automatically re-ticked. Setting the csmt registry key to 0 or 1 also has no effect. I'll have to go back to 3.3 for now.

**Comment by IngeniousDox** [comment]
Like I said there, and in the WoW Test Results issue: CSMT is removed from Staging. If you built from tag/release 3.5 from Staging yourself, you can click the checkbox in the Staging Tab and it will disable the dll redirect and it should work.

However, and I'm guessing here, I think you built from current Staging git, which already has the fixed checkbox that actually toggles the normal CSMT now. So your checkbox can't unset it anymore. You will have to open registry and remove the DllRedirect by hand.

**Comment by goldpaw** [comment]
@TomBZombie you do remember to reset / recreate your wine prefix after upgrading wine, right? 

They removed wined3d-csmt.dll in staging 3.4, and if you created your prefix in 3.3 or earlier, it would probably still have a redirect that now doesn't work.

**Comment by Firerat** [comment]
regards the wined3d-csmt bug
just edit ~/.wineprefix/user.reg
and delete the wined3d-csmt.dll line

I might create a patch for upstream which will silently fix this issue.. for those who can't figure out why it is 'broke'

**Comment by goldpaw** [comment]
@Firerat seeing how the problem is in the redirects found in the prefixes and not directly part of the wine installation itself, I'm wondering out of curiousity how you would go about fixing it? Adding in a wined3d-csmt.dll that is a shortcut to wined3d.dll in wine? :/

**Comment by Firerat** [comment]
@goldpaw , nah.. something must look at user.reg to know about the redirect
so find what looks for the redirects, and tell it to ignore wined3d-csmt
I havn't looked at the code yet

**Comment by goldpaw** [comment]
Ah, a matter of patching into the redirect code. Got it. :)

**Comment by qwertychouskie** [comment]
Probably the best way to do it is to only use the redirect if the file exists.  This would solve any issue of a redirect to a non-existent DLL, not just this one.

**Comment by Firerat** [comment]
@goldpaw @qwertychouskie 
looks like this has been done in staging 
https://github.com/wine-staging/wine-staging/commit/f6fdc7705e9e17939df8b4aeb54da8dd82dcb99e

**Comment by goldpaw** [comment]
So basically the idea should be to replace the ERR when the redirect fails with a FIXME?
